In [2]:
# Importing Libraries
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup 
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [3]:
df.sample()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
128312,Data Analyst,Financial Data Analyst (H/F) - Alternance,"Paris, France",via LinkedIn,Full-time,False,France,2023-08-25 08:18:57,False,False,France,NaN,NaN,NaN,Publicis Sapient France,"['vba', 'power bi', 'excel']","{'analyst_tools': ['power bi', 'excel'], 'prog..."

In [4]:
df.sample(10)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
722203,Data Analyst,Data Analyst Tableau Developer - Insurance/Rei...,"Stamford, CT",via LinkedIn,Full-time,False,"New York, United States",2023-08-31 21:00:20,False,False,United States,NaN,NaN,NaN,OdysseyRe,"['sql', 'tableau', 'excel']","{'analyst_tools': ['tableau', 'excel'], 'progr..."
622738,Cloud Engineer,Senior Cloud Support Engineer,"Warsaw, Poland",via Praca Trabajo.org,Full-time,False,Poland,2023-08-30 12:32:06,False,False,Poland,NaN,NaN,NaN,Snowflake,"['sql', 'python', 'java', 'r', 'snowflake', 'a...","{'cloud': ['snowflake', 'aws', 'azure', 'gcp']..."
721552,Data Engineer,DATA ENGINEER: INFORMATICA,United States,via SimplyHired,Full-time,False,Georgia,2023-01-31 22:33:55,False,False,United States,NaN,NaN,NaN,UniGroup,"['sql', 'python', 'snowflake', 'aws', 'kafka',...","{'cloud': ['snowflake', 'aws'], 'libraries': [..."
99072,Data Analyst,Data analyst and Developer,Georgia,via Indeed,Full-time,False,Georgia,2023-11-29 00:41:15,False,False,United States,NaN,NaN,NaN,Bentley Systems,"['sql', 'snowflake', 'qlik']","{'analyst_tools': ['qlik'], 'cloud': ['snowfla..."
326814,Senior Data Scientist,Think Big Analytics Sr Data Scientist /シニアデータサ...,"Tokyo, Japan",via エリートネットワーク,Full-time,False,Japan,2023-01-20 00:03:25,False,False,Japan,NaN,NaN,NaN,データウェアハウス企業,"['r', 'python', 'sql', 'nosql', 'hadoop']","{'libraries': ['hadoop'], 'programming': ['r',..."
750973,Senior Data Scientist,(Senior) Manager Data Science (w/m/d),"Frankfurt, Germany",via XING,Full-time,False,Germany,2023-10-06 20:12:38,False,False,Germany,NaN,NaN,NaN,BDO AG Wirtschaftsprüfungsgesellschaft,"['python', 'r', 'java', 'tensorflow', 'pytorch']","{'libraries': ['tensorflow', 'pytorch'], 'prog..."
551134,Data Scientist,Sr. Solution Engineer (Data Scientist) German ...,Anywhere,via Indeed,Full-time,True,Austria,2023-06-16 20:08:05,False,False,Austria,NaN,NaN,NaN,DeepOpinion,"['python', 'bash', 'numpy', 'scikit-learn', 'm...","{'libraries': ['numpy', 'scikit-learn', 'matpl..."
269977,Data Engineer,Data Engineer,"Madrid, Spain",via BeBee,Full-time,False,Spain,2023-04-28 07:17:12,True,False,Spain,NaN,NaN,NaN,Nommon Solutions and Technologies,"['python', 'mongo', 'java', 'no-sql', 'aws', '...","{'analyst_tools': ['tableau', 'qlik', 'power b..."
439750,Data Analyst,2023 Launch Program: Associate Data Analyst In...,"Charlotte, NC",via Startupers,Full-time,False,Georgia,2023-02-09 17:26:20,False,True,United States,NaN,NaN,NaN,Red Ventures,"['python', 'sql', 'spring', 'pandas', 'tableau']","{'analyst_tools': ['tableau'], 'libraries': ['..."
633305,Data Scientist,Sr. Data Scientist,"Boston, MA",via LinkedIn,Full-time,False,"New York, United States",2023-06-27 12:03:51,False,False,United States,NaN,NaN,NaN,Plymouth Rock Assurance,"['python', 'r', 'sas', 'sas']","{'analyst_tools': ['sas'], 'programming': ['py..."

In [6]:
dataset = load_dataset('lukebarousse/data_jobs')
df_original = dataset['train'].to_pandas()

df_altered = df_original.copy()


print('ID of df_original: ', id(df_original))
print('ID of df_altered: ', id(df_altered))
print('Are the two dataframes same? ', id(df_original)==id(df_altered))

ID of df_original:  2787714503952
ID of df_altered:  2787552825296
Are the two dataframes same?  False

In [9]:
median_salary = df_altered['salary_year_avg'].median()
df_altered['salary_year_avg'] = df_altered['salary_year_avg'].fillna(median_salary)

df_altered.loc[:5, 'salary_year_avg']

0    115000.0
1    115000.0
2    115000.0
3    115000.0
4    115000.0
5    115000.0
Name: salary_year_avg, dtype: float64

In [11]:
df_original.loc[:5, 'salary_year_avg']

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
Name: salary_year_avg, dtype: float64